image: python:3.9

pages:
  stage: deploy
  only:
    - master
  script:
    - pip install mkdocs-material mkdocs-macros-plugin
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public