site_name: CTF Docs
theme:
  name: material
  favicon: assets/img/favicon.ico
  logo: assets/img/favicon.ico
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/xanhacks/ctf-docs
repo_name: xanhacks/ctf-docs

extra:
  homepage: https://xanhacks.gitlab.io/ctf-docs/welcome/
  base_url: https://xanhacks.gitlab.io/ctf-docs
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xanhacks
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/xanhacks
    - icon: fontawesome/solid/globe
      link: https://xanhacks.xyz


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - admonition
  - def_list

plugins:
  - macros

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - assets/js/config.js
  - assets/js/matomo.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
