site_name: CTF Docs
theme:
  name: material
  favicon: assets/img/favicon.ico
  logo: assets/img/favicon.ico
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/xanhacks/ctf-docs
repo_name: xanhacks/ctf-docs

extra:
  homepage: https://docs.xanhacks.xyz/
  base_url: https://docs.xanhacks.xyz/
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xanhacks
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/xanhacks
    - icon: fontawesome/solid/globe
      link: https://xanhacks.xyz


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - admonition
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - macros
  - search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/config.js
  - assets/js/matomo.js
  - assets/js/mathjax.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
